# ESPHome config for RecPro/Houghton AC control (CARRIER_AC128 protocol)
# Tested on ESP8285 ESP-01M IR transceiver module (GPIO4 TX, GPIO14 RX)

esphome:
  name: ac-controller

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome

logger:
  level: DEBUG
  baud_rate: 0  # Disable serial logging (ESP-01 has limited pins)

external_components:
  - source: github://mrmees/esphome-carrier-ac128
    components: [carrier_ac128]

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

remote_receiver:
  id: ir_receiver
  pin:
    number: GPIO14
    inverted: true  # Most IR demodulators output active-low

time:
  - platform: homeassistant
    id: ha_time

climate:
  - platform: carrier_ac128
    name: "Houghton AC"
    time_id: ha_time
    receiver_id: ir_receiver
